baseURL = "https://mirrors.cqu.edu.cn/wiki/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/cqumirror/mirror-wiki/tree/master/content/"
  # Author of the site, will be used in meta information
  author = "lanunion-editor"
  # Description of the site, will be used in meta information
  description = "editors"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  # English is the default language
  defaultContentLanguage = "zh"
  # Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= false
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.zh]
title = "cqumirror-wiki"
weight = 1
languageName = "简体中文"

#[[Languages.zh.menu.shortcuts]]
#name = "<i class='fa fa-fw fa-github'></i> Github repo"
#identifier = "ds"
#url = "https://github.com/matcornic/hugo-theme-learn"
#weight = 10

#[[Languages.zh.menu.shortcuts]]
#name = "<i class='fa fa-fw fa-camera'></i> Showcases"
#url = "showcase"
#weight = 11

#[[Languages.zh.menu.shortcuts]]
#name = "<i class='fa fa-fw fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[Languages.zh.menu.shortcuts]]
#name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30
